Repository woorifisa-projects/woochacha, pull requests merged in 2023-08, with the labels that each got.

#3 [docs] pr 템플릿 테스트, 프론트엔드 및 백엔드 폴더 구조 세팅
  backend/test.md
  frontend/test.md
Labels: 개발환경 세팅

#5 [init] 프론트엔드 프로젝트 세팅
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/.prettierrc
  frontend/README.md
  frontend/jsconfig.json
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/public/favicon.ico
  frontend/public/next.svg
  frontend/public/vercel.svg
  frontend/src/pages/_app.js
  frontend/src/pages/_document.js
  frontend/src/pages/api/hello.js
  frontend/src/pages/index.js
  frontend/src/styles/globals.css
  frontend/src/styles/theme.js
  frontend/src/utils/createEmotionCache.js
  frontend/tailwind.config.js
  frontend/test.md
Labels: 개발환경 세팅

#13 [feat] 기본적인 공통 레이아웃 구성
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/CopyRight.js
  frontend/src/components/MenuAppbar.js
  frontend/src/components/ProfileAppbar.js
  frontend/src/constants/String.js
  frontend/src/layouts/DefaultFooter.js
  frontend/src/layouts/DefaultHeader.js
  frontend/src/layouts/Layout.js
  frontend/src/pages/_app.js
  frontend/src/pages/capitals/index.js
  frontend/src/pages/index.js
  frontend/src/pages/mypage/index.js
  frontend/src/pages/products/index.js
  frontend/src/pages/products/sale.js
  frontend/src/pages/users/login.js
  frontend/src/pages/users/signup.js
  frontend/src/styles/globals.css
  frontend/src/styles/theme.js
Labels: 개발환경 세팅, 디자인

#20 [feat] 백엔드 회원가입
  .idea/.gitignore
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/workspace.xml
  .vscode/settings.json
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/woochacha/backend/BackendApplication.java
  backend/src/main/java/com/woochacha/backend/common/CommonResponse.java
  backend/src/main/java/com/woochacha/backend/common/ModelMapping.java
  backend/src/main/java/com/woochacha/backend/common/README.md
  backend/src/main/java/com/woochacha/backend/config/QueryDslConfig.java
  backend/src/main/java/com/woochacha/backend/config/README.md
  backend/src/main/java/com/woochacha/backend/config/WebConfig.java
  backend/src/main/java/com/woochacha/backend/domain/member/controller/MemberController.java
  backend/src/main/java/com/woochacha/backend/domain/member/controller/README.md
  backend/src/main/java/com/woochacha/backend/domain/member/dto/LoginRequestDto.java
  backend/src/main/java/com/woochacha/backend/domain/member/dto/README.md
  backend/src/main/java/com/woochacha/backend/domain/member/dto/SignUpRequestDto.java
  backend/src/main/java/com/woochacha/backend/domain/member/dto/SignUpResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/member/entity/Member.java
  backend/src/main/java/com/woochacha/backend/domain/member/entity/MemberInfo.java
  backend/src/main/java/com/woochacha/backend/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/woochacha/backend/domain/member/repository/README.md
  backend/src/main/java/com/woochacha/backend/domain/member/service/README.md
  backend/src/main/java/com/woochacha/backend/domain/member/service/SignService.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/impl/SignServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/security/controller/README.md
  backend/src/main/java/com/woochacha/backend/domain/security/dto/README.md
  backend/src/main/java/com/woochacha/backend/domain/security/exception/README.md
  backend/src/main/java/com/woochacha/backend/domain/security/repository/README.md
  backend/src/main/java/com/woochacha/backend/domain/security/service/README.md
  backend/src/main/java/com/woochacha/backend/security/configs/SecurityConfig.java
  backend/src/main/resources/application.properties
Labels: 기능, 백엔드

#22 [design] 로그인, 회원가입 UI 레이아웃 구성
  frontend/public/favicon.ico
  frontend/public/next.svg
  frontend/public/vercel.svg
  frontend/src/components/common/CopyRight.js
  frontend/src/components/common/MenuAppbar.js
  frontend/src/components/common/ProfileAppbar.js
  frontend/src/constants/RegExp.js
  frontend/src/hooks/useChecks.js
  frontend/src/layouts/DefaultFooter.js
  frontend/src/layouts/DefaultHeader.js
  frontend/src/pages/users/login.js
  frontend/src/pages/users/signup.js
Labels: 프론트엔드, 디자인

#25 [feat] 로그인 back-end 기본 기능 구현
  backend/.gitignore
  backend/src/main/java/com/woochacha/backend/config/JwtSecurityConfig.java
  backend/src/main/java/com/woochacha/backend/domain/jwt/JwtAccessDeniedHandler.java
  backend/src/main/java/com/woochacha/backend/domain/jwt/JwtAuthenticationEntryPoint.java
  backend/src/main/java/com/woochacha/backend/domain/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/com/woochacha/backend/domain/jwt/JwtAuthorizationFilter.java
  backend/src/main/java/com/woochacha/backend/domain/jwt/JwtFilter.java
  backend/src/main/java/com/woochacha/backend/domain/jwt/JwtTokenProvider.java
  backend/src/main/java/com/woochacha/backend/domain/member/controller/MemberController.java
  backend/src/main/java/com/woochacha/backend/domain/member/dto/LoginResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/member/entity/Member.java
  backend/src/main/java/com/woochacha/backend/domain/member/exception/LoginException.java
  backend/src/main/java/com/woochacha/backend/domain/member/exception/README.md
  backend/src/main/java/com/woochacha/backend/domain/member/exception/SignUpException.java
  backend/src/main/java/com/woochacha/backend/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/SignService.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/impl/SignServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/impl/UserDetailsServiceImpl.java
  backend/src/main/java/com/woochacha/backend/security/configs/SecurityConfig.java
Labels: 기능, 백엔드

#29 [feat] 회원가입 기능 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/auth/LoginForm.js
  frontend/src/components/auth/SignupForm.js
  frontend/src/hooks/useChecks.js
  frontend/src/pages/users/login.js
  frontend/src/pages/users/signup.js
  frontend/src/services/authApi.js
  frontend/src/utils/api.js
  frontend/src/utils/validate.js
Labels: 기능, 프론트엔드

#33 [feat] ModelMapper Singleton 패턴 적용
  backend/.gitignore
  backend/src/main/java/com/woochacha/backend/common/ModelMapping.java
  backend/src/main/java/com/woochacha/backend/domain/member/controller/MemberController.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/SignService.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/impl/SignServiceImpl.java
  backend/src/main/java/com/woochacha/backend/security/configs/SecurityConfig.java
Labels: 리팩터링, 백엔드

#34 [remove] SignServiceImpl.java remove modelmapperInit()
  backend/src/main/java/com/woochacha/backend/domain/member/service/impl/SignServiceImpl.java
Labels: 리팩터링, 백엔드

#36 [feat] AWS S3 연동 및 사용자 프로필 사진 업로드, 매물 사진 리스트 업로드 기능 구현
  backend/build.gradle
  backend/src/main/java/com/woochacha/backend/config/S3Config.java
  backend/src/main/java/com/woochacha/backend/config/WebConfig.java
  backend/src/main/java/com/woochacha/backend/domain/AmazonS3/controller/AmazonS3Controller.java
  backend/src/main/java/com/woochacha/backend/domain/AmazonS3/dto/AmazonS3ProductRequestDto.java
  backend/src/main/java/com/woochacha/backend/domain/AmazonS3/dto/AmazonS3RequestDto.java
  backend/src/main/java/com/woochacha/backend/domain/AmazonS3/service/AmazonS3Service.java
  backend/src/main/java/com/woochacha/backend/domain/AmazonS3/service/AmazonS3ServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/impl/SignServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/product/entity/CarImage.java
  backend/src/main/java/com/woochacha/backend/domain/product/entity/Product.java
  backend/src/main/java/com/woochacha/backend/domain/product/repository/CarImageRepository.java
  backend/src/main/java/com/woochacha/backend/domain/product/repository/ProductRepository.java
  backend/src/main/java/com/woochacha/backend/security/configs/SecurityConfig.java
Labels: 기능, 백엔드

#38 [feat] 로그인 기능 구현
  frontend/.eslintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/atoms/userInfoAtoms.js
  frontend/src/components/auth/LoginForm.js
  frontend/src/components/auth/SignupForm.js
  frontend/src/components/common/ProfileAppbar.js
  frontend/src/constants/String.js
  frontend/src/hooks/withAuth.js
  frontend/src/layouts/DefaultHeader.js
  frontend/src/pages/mypage/index.js
  frontend/src/services/authApi.js
  frontend/src/utils/api.js
  frontend/src/utils/localStorage.js
Labels: 기능, 프론트엔드

#37 [feat] 마이페이지 등록한 매물 조회 기능 구현 back-end
  backend/build.gradle
  backend/src/main/java/com/woochacha/backend/domain/car/detail/entity/CarDetail.java
  backend/src/main/java/com/woochacha/backend/domain/car/detail/entity/CarName.java
  backend/src/main/java/com/woochacha/backend/domain/car/detail/entity/CarOption.java
  backend/src/main/java/com/woochacha/backend/domain/car/info/entity/AccidentType.java
  backend/src/main/java/com/woochacha/backend/domain/car/info/entity/CarAccidentInfo.java
  backend/src/main/java/com/woochacha/backend/domain/car/info/entity/CarExchangeInfo.java
  backend/src/main/java/com/woochacha/backend/domain/car/info/entity/PartType.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/entity/Color.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/entity/Fuel.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/entity/Model.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/entity/Transmission.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/entity/Type.java
  backend/src/main/java/com/woochacha/backend/domain/log/entity/Log.java
  backend/src/main/java/com/woochacha/backend/domain/member/dto/SignUpResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/member/entity/Member.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/SignService.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/impl/SignServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/controller/MypageController.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/dto/ProductResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/repository/MypageRepository.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/service/MypageService.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/service/impl/MypageServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/product/entity/CarImage.java
  backend/src/main/java/com/woochacha/backend/domain/product/entity/Product.java
  backend/src/main/java/com/woochacha/backend/domain/purchase/entity/PurchaseForm.java
  backend/src/main/java/com/woochacha/backend/domain/sale/entity/Branch.java
  backend/src/main/java/com/woochacha/backend/domain/sale/entity/SaleForm.java
  backend/src/main/java/com/woochacha/backend/domain/status/entity/CarStatus.java
  backend/src/main/java/com/woochacha/backend/domain/status/entity/CarStatusList.java
  backend/src/main/java/com/woochacha/backend/domain/transaction/entity/Transaction.java
  backend/src/main/java/com/woochacha/backend/security/configs/SecurityConfig.java
Labels: 기능, 백엔드

#45 [fix] front build 관련 에러 해결
  frontend/next.config.js
  frontend/package.json
Labels: 버그, 인프라

#46 [feat] 백엔드 마이페이지 판매이력 조회
  backend/src/main/java/com/woochacha/backend/domain/mypage/controller/MypageController.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/repository/MypageRepository.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/service/impl/MypageServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/product/entity/Product.java
Labels: 기능, 백엔드

#47 [feat] 백엔드 마이페이지 구매이력 조회
  backend/src/main/java/com/woochacha/backend/domain/mypage/controller/MypageController.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/repository/MypageRepository.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/service/impl/MypageServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/product/entity/Product.java
Labels: 기능, 백엔드

#49 [fix] front import 관련 에러
  frontend/src/components/common/MenuAppbar.js
  frontend/src/components/common/ProfileAppbar.js
  frontend/src/layouts/DefaultHeader.js
  frontend/src/utils/validate.js
Labels: 버그

#57 [design] 메인페이지 UI 레이아웃 구성
  frontend/src/components/common/MenuAppbar.js
  frontend/src/components/common/ProfileAppbar.js
  frontend/src/components/common/SelectBox.js
  frontend/src/components/product/MainProduct.js
  frontend/src/components/product/SearchBar.js
  frontend/src/constants/regExp.js
  frontend/src/constants/string.js
  frontend/src/layouts/DefaultHeader.js
  frontend/src/pages/index.js
  frontend/src/styles/theme.js
  frontend/src/utils/validate.js
Labels: 프론트엔드, 디자인

#65 [feat] 백엔드 프로필 조회 기능 구현
  backend/src/main/java/com/woochacha/backend/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/controller/MypageController.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/dto/ProductResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/repository/MypageRepository.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/service/impl/MypageServiceImpl.java
Labels: 기능, 백엔드

#66 [design] 대출페이지 UI 레이아웃 구성
  frontend/src/components/common/MainCard.js
  frontend/src/components/common/MiniCard.js
  frontend/src/constants/string.js
  frontend/src/pages/capitals/index.js
Labels: 프론트엔드, 디자인

#68 [feat]] QLDB 환경 셋팅 및 QLDB 기본 조회 기능 구현
  backend/build.gradle
  backend/src/main/java/com/woochacha/backend/config/QldbConfig.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/dto/ProfileDto.java
  backend/src/main/java/com/woochacha/backend/domain/purchase/entity/PurchaseForm.java
  backend/src/main/java/com/woochacha/backend/domain/qldb/service/QldbService.java
  backend/src/main/java/com/woochacha/backend/domain/qldb/service/serviceImpl/QldbServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/status/entity/CarStatusList.java
Labels: 기능, 개발환경 세팅, 백엔드

#72 [feat] 매물 상세 조회 기능 구현
  backend/src/main/java/com/woochacha/backend/config/WebConfig.java
  backend/src/main/java/com/woochacha/backend/domain/car/detail/entity/CarOptionList.java
  backend/src/main/java/com/woochacha/backend/domain/car/info/entity/CarExchangeInfo.java
  backend/src/main/java/com/woochacha/backend/domain/car/info/entity/ExchangeType.java
  backend/src/main/java/com/woochacha/backend/domain/car/info/entity/ExchangeTypeList.java
  backend/src/main/java/com/woochacha/backend/domain/product/controller/ProductController.java
  backend/src/main/java/com/woochacha/backend/domain/product/dto/ProductDetailResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/product/dto/detail/ProductAccidentInfo.java
  backend/src/main/java/com/woochacha/backend/domain/product/dto/detail/ProductBasicInfo.java
  backend/src/main/java/com/woochacha/backend/domain/product/dto/detail/ProductDetailInfo.java
  backend/src/main/java/com/woochacha/backend/domain/product/dto/detail/ProductExchangeInfo.java
  backend/src/main/java/com/woochacha/backend/domain/product/dto/detail/ProductOptionInfo.java
  backend/src/main/java/com/woochacha/backend/domain/product/dto/detail/ProductOwnerInfo.java
  backend/src/main/java/com/woochacha/backend/domain/product/service/ProductService.java
  backend/src/main/java/com/woochacha/backend/domain/product/service/impl/ProductServiceImpl.java
Labels: 기능, 백엔드

#71 [chore] 마이페이지 상품 제목 데이터 수정
  backend/src/main/java/com/woochacha/backend/domain/mypage/controller/MypageController.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/dto/ProductResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/dto/ProfileDto.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/repository/MypageRepository.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/service/impl/MypageServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/product/entity/CarImage.java
  backend/src/main/java/com/woochacha/backend/domain/product/entity/Product.java
  backend/src/main/java/com/woochacha/backend/domain/transaction/entity/Transaction.java
Labels: 리팩터링, 백엔드

#74 [design] 구매페이지 UI 레이아웃 구성
  frontend/src/components/common/MiniCard.js
  frontend/src/components/product/FilterSideBar.js
  frontend/src/components/product/ProductCard.js
  frontend/src/constants/string.js
  frontend/src/pages/capitals/index.js
  frontend/src/pages/products/detail/[productId].js
  frontend/src/pages/products/index.js
Labels: 프론트엔드, 디자인

#81 [Feat] 차량 판매 신청 및 신청 가능 여부 기능 구현
  backend/src/main/java/com/woochacha/backend/domain/qldb/service/QldbService.java
  backend/src/main/java/com/woochacha/backend/domain/qldb/service/serviceImpl/QldbServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/sale/controller/README.md
  backend/src/main/java/com/woochacha/backend/domain/sale/controller/SaleController.java
  backend/src/main/java/com/woochacha/backend/domain/sale/dto/README.md
  backend/src/main/java/com/woochacha/backend/domain/sale/dto/SaleFormRequestDto.java
  backend/src/main/java/com/woochacha/backend/domain/sale/entity/SaleForm.java
  backend/src/main/java/com/woochacha/backend/domain/sale/exception/README.md
  backend/src/main/java/com/woochacha/backend/domain/sale/repository/BranchRepository.java
  backend/src/main/java/com/woochacha/backend/domain/sale/repository/README.md
  backend/src/main/java/com/woochacha/backend/domain/sale/repository/SaleFormRepository.java
  backend/src/main/java/com/woochacha/backend/domain/sale/service/README.md
  backend/src/main/java/com/woochacha/backend/domain/sale/service/SaleFormApplyService.java
  backend/src/main/java/com/woochacha/backend/domain/sale/service/SaleFormApplyServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/status/repository/CarStatusRepository.java
Labels: 기능, 백엔드

#79 [chore] 헤더, 푸터 디자인 수정
  frontend/src/components/common/ProfileAppbar.js
  frontend/src/constants/string.js
  frontend/src/layouts/DefaultFooter.js
  frontend/src/layouts/DefaultHeader.js
Labels: 프론트엔드, 디자인, 수정

#77 [Chore] 회원가입 시 기본 프로필 이미지 설정&로그인 응답에 이름, 아이디 추가&로그인 응답 헤더에 토큰 추가
  backend/src/main/java/com/woochacha/backend/domain/member/controller/MemberController.java
  backend/src/main/java/com/woochacha/backend/domain/member/dto/LoginResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/member/dto/SignUpRequestDto.java
  backend/src/main/java/com/woochacha/backend/domain/member/entity/Member.java
  backend/src/main/java/com/woochacha/backend/domain/member/exception/LoginException.java
  backend/src/main/java/com/woochacha/backend/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/SignService.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/impl/SignServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/impl/UserDetailsServiceImpl.java
Labels: 백엔드, 수정

#76 [Feat] 백엔드 마이페이지 사용자별 구매 요청 내역 조회
  .idea/workspace.xml
  backend/src/main/java/com/woochacha/backend/domain/mypage/controller/MypageController.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/dto/ProductResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/dto/PurchaseReqeustListDto.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/repository/MypageRepository.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/service/impl/MypageServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/product/entity/Product.java
  backend/src/main/java/com/woochacha/backend/domain/purchase/entity/PurchaseForm.java
Labels: 기능, 백엔드

#80 [Feat] 백엔드 판매 요청폼 조회 기능 구현
  backend/src/main/java/com/woochacha/backend/domain/mypage/controller/MypageController.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/dto/EditProductDto.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/dto/SaleFormDto.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/repository/MypageRepository.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/service/impl/MypageServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/sale/repository/SaleFormRepository.java
Labels: 기능, 백엔드

#85 [Chore] 에러 코드 수정
  backend/src/main/java/com/woochacha/backend/domain/mypage/controller/MypageController.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/dto/SaleFormDto.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/repository/MypageRepository.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/service/impl/MypageServiceImpl.java
Labels: 버그, 수정

#83 [Feat] 매물 전체 조회 시 필터링 목록 데이터, product id를 포함하여 전달
  backend/src/main/java/com/woochacha/backend/domain/car/detail/dto/CarNameDto.java
  backend/src/main/java/com/woochacha/backend/domain/car/detail/dto/README.md
  backend/src/main/java/com/woochacha/backend/domain/car/type/dto/ColorDto.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/dto/FuelDto.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/dto/ModelDto.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/dto/README.md
  backend/src/main/java/com/woochacha/backend/domain/car/type/dto/TrasmissionDto.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/dto/TypeDto.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/entity/TypeList.java
  backend/src/main/java/com/woochacha/backend/domain/product/controller/ProductController.java
  backend/src/main/java/com/woochacha/backend/domain/product/dto/ProdcutAllResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/product/dto/all/ProductFilterInfo.java
  backend/src/main/java/com/woochacha/backend/domain/product/dto/all/ProductInfo.java
  backend/src/main/java/com/woochacha/backend/domain/product/service/ProductService.java
  backend/src/main/java/com/woochacha/backend/domain/product/service/impl/ProductServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/sale/dto/BranchDto.java
Labels: 기능, 백엔드, 수정

#87 [design] 마이페이지 UI 레이아웃 구성
  frontend/src/components/mypage/MypageCard.js
  frontend/src/components/mypage/MypageProfile.js
  frontend/src/components/mypage/MypageSidebar.js
  frontend/src/layouts/user/UserMyPageLayout.js
  frontend/src/pages/_app.js
  frontend/src/pages/mypage/[userId].js
  frontend/src/pages/mypage/index.js
  frontend/src/pages/mypage/profile/edit/[userId].js
  frontend/src/pages/mypage/purchase-request/[userId].js
  frontend/src/pages/mypage/purchase/[userId].js
  frontend/src/pages/mypage/registered/[userId].js
  frontend/src/pages/mypage/registered/edit/[userId]/[productId].js
  frontend/src/pages/mypage/sale-request/[userId].js
  frontend/src/pages/mypage/sale/[userId].js
Labels: 기능, 프론트엔드, 디자인

#90 [chore] back 연동 관련 수정
  frontend/next.config.js
  frontend/src/pages/index.js
  frontend/src/services/productApi.js
  frontend/src/utils/api.js
Labels: 개발환경 세팅, 프론트엔드

#92 [chore] 폴더명 수정 및 포트 설정
  frontend/src/pages/product/detail/[productId].js
  frontend/src/pages/product/index.js
  frontend/src/pages/product/sale.js
  frontend/src/utils/api.js
Labels: 개발환경 세팅, 프론트엔드

#94 [Build] webconfig allowedOrigins front-end port update
  backend/src/main/java/com/woochacha/backend/config/WebConfig.java
  frontend/next.config.js
  frontend/src/constants/string.js
  frontend/src/utils/api.js
Labels: 인프라

#101 [Build] SecurityConfig.java HttpMethod.OPTIONS permitAll
  backend/src/main/java/com/woochacha/backend/config/WebConfig.java
  backend/src/main/java/com/woochacha/backend/domain/jwt/JwtFilter.java
  backend/src/main/java/com/woochacha/backend/security/configs/SecurityConfig.java
Labels: 인프라

#106 [Build] FrontEnd<->BackEnd 통신 중 Cors OPTIONS 403 해결
  backend/src/main/java/com/woochacha/backend/config/WebConfig.java
  backend/src/main/java/com/woochacha/backend/domain/jwt/JwtAuthenticationEntryPoint.java
  backend/src/main/java/com/woochacha/backend/domain/jwt/JwtAuthorizationFilter.java
  backend/src/main/java/com/woochacha/backend/domain/jwt/JwtFilter.java
  backend/src/main/java/com/woochacha/backend/domain/jwt/JwtTokenProvider.java
  backend/src/main/java/com/woochacha/backend/security/configs/SecurityConfig.java
Labels: 인프라, 에러 처리

#95 [Feat] 상품 가격 수정 신청 기능 구현
  backend/src/main/java/com/woochacha/backend/domain/mypage/controller/MypageController.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/dto/EditProductDto.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/dto/UpdatePriceDto.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/repository/MypageRepository.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/service/impl/MypageServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/product/entity/Product.java
  backend/src/main/java/com/woochacha/backend/domain/product/repository/ProductRepository.java
  backend/src/main/java/com/woochacha/backend/domain/status/entity/CarStatusList.java
Labels: 기능, 백엔드

#105 [feat] 차량 점검 후 승인 기능 구현
  backend/build.gradle
  backend/src/main/java/com/woochacha/backend/domain/admin/controller/ApproveSaleController.java
  backend/src/main/java/com/woochacha/backend/domain/admin/controller/README.md
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/ApproveSaleResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/CarInspectionInfoDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/CarInspectionRequestDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/README.md
  backend/src/main/java/com/woochacha/backend/domain/admin/exception/README.md
  backend/src/main/java/com/woochacha/backend/domain/admin/repository/README.md
  backend/src/main/java/com/woochacha/backend/domain/admin/service/ApproveSaleService.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/ApproveSaleServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/README.md
  backend/src/main/java/com/woochacha/backend/domain/qldb/service/QldbService.java
  backend/src/main/java/com/woochacha/backend/domain/qldb/service/serviceImpl/QldbServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/sale/controller/SaleController.java
  backend/src/main/java/com/woochacha/backend/domain/sale/dto/BranchDto.java
  backend/src/main/java/com/woochacha/backend/domain/sale/dto/SaleFormRequestDto.java
  backend/src/main/java/com/woochacha/backend/domain/sale/service/SaleFormApplyServiceImpl.java
Labels: 기능, 에러 처리, 백엔드, 수정

#108 [feat] 차량 accident의 block id 값을 가지고와 history를 조회하는 기능 구현
  backend/src/main/java/com/woochacha/backend/domain/qldb/service/QldbService.java
  backend/src/main/java/com/woochacha/backend/domain/qldb/service/serviceImpl/QldbServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/sale/service/SaleFormApplyServiceImpl.java
Labels: 기능, 백엔드, 수정

#111 [design] 마이페이지 프로필 조회 / 수정 페이지 기본 UI 레이아웃 구성
  frontend/src/components/common/FileUpload.js
  frontend/src/components/mypage/MypageProfile.js
  frontend/src/components/mypage/MypageProfileEdit.js
  frontend/src/pages/mypage/[userId].js
  frontend/src/pages/mypage/profile/edit/[userId].js
  frontend/src/services/profileApi.js
Labels: 기능, 프론트엔드, 디자인

#121 [Feature] 키워드 검색 기능 구현&필터링 검색 BooleanBuilder 사용 제거 리팩토링
  backend/src/main/java/com/woochacha/backend/domain/product/controller/ProductController.java
  backend/src/main/java/com/woochacha/backend/domain/product/service/ProductService.java
  backend/src/main/java/com/woochacha/backend/domain/product/service/impl/ProductServiceImpl.java
Labels: 기능, 리팩터링, 백엔드

#123 [feat] 사용자 구매 신청 기능 구현
  backend/src/main/java/com/woochacha/backend/domain/product/controller/ProductController.java
  backend/src/main/java/com/woochacha/backend/domain/product/dto/ProductPurchaseRequestDto.java
  backend/src/main/java/com/woochacha/backend/domain/product/entity/CarImage.java
  backend/src/main/java/com/woochacha/backend/domain/product/service/ProductService.java
  backend/src/main/java/com/woochacha/backend/domain/product/service/impl/ProductServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/purchase/controller/PurchaseController.java
  backend/src/main/java/com/woochacha/backend/domain/purchase/controller/README.md
  backend/src/main/java/com/woochacha/backend/domain/purchase/dto/README.md
  backend/src/main/java/com/woochacha/backend/domain/purchase/entity/PurchaseForm.java
  backend/src/main/java/com/woochacha/backend/domain/purchase/exception/README.md
  backend/src/main/java/com/woochacha/backend/domain/purchase/repository/PurchaseFormRepository.java
  backend/src/main/java/com/woochacha/backend/domain/purchase/repository/README.md
  backend/src/main/java/com/woochacha/backend/domain/purchase/service/PurchaseApplyService.java
  backend/src/main/java/com/woochacha/backend/domain/purchase/service/README.md
  backend/src/main/java/com/woochacha/backend/domain/purchase/service/serviceImpl/PurchaseApplyServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/sale/controller/SaleController.java
  backend/src/main/java/com/woochacha/backend/domain/sale/service/SaleFormApplyService.java
  backend/src/main/java/com/woochacha/backend/domain/sale/service/SaleFormApplyServiceImpl.java
Labels: 기능, 백엔드
