Repository woorifisa-projects/woochacha, pull requests merged in 2023-09, with the labels that each got.

#127 [feat] 관리자가 member를 관리하는 기능을 구현
  backend/src/main/java/com/woochacha/backend/domain/admin/controller/ApproveSaleController.java
  backend/src/main/java/com/woochacha/backend/domain/admin/controller/ManageMemberController.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/approve/ApproveSaleResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/approve/CarAccidentInfoDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/approve/CarExchangeInfoDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/approve/CarInspectionInfoResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/approve/CompareRequestDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/approve/RegisterProductDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/manageMember/EditMemberRequestDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/manageMember/MemberInfoListResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/manageMember/MemberInfoResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/ApproveSaleService.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/ManageMemberService.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/RegisterProductService.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/ApproveSaleServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/ManageMemberServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/RegisterProductServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/woochacha/backend/domain/qldb/service/QldbService.java
Labels: 기능, 백엔드

#125 [feature] 메인페이지 백엔드 api 연동
  frontend/src/components/product/DetailProduct.js
  frontend/src/components/product/MultipleSelect.js
  frontend/src/components/product/ProductCard.js
  frontend/src/pages/index.js
  frontend/src/pages/product/detail/[productId].js
  frontend/src/services/productApi.js
Labels: 기능, 프론트엔드

#129 [design] 관리자 메뉴 전체적인 UI 레이아웃 구성
  frontend/src/components/admin/AdminMenuAppbar.js
  frontend/src/components/admin/AdminpageSidebar.js
  frontend/src/components/common/BasicTable.js
  frontend/src/constants/string.js
  frontend/src/layouts/DefaultHeader.js
  frontend/src/layouts/admin/AdminPageLayout.js
  frontend/src/pages/admin/members/[memberId].js/index.js
  frontend/src/pages/admin/members/[memberId].js/log.js
  frontend/src/pages/admin/members/edit/[memberId].js
  frontend/src/pages/admin/members/index.js
  frontend/src/pages/admin/product/edit/[productId].js
  frontend/src/pages/admin/product/index.js
  frontend/src/pages/admin/purchase/[purchaseId].js
  frontend/src/pages/admin/purchase/index.js
  frontend/src/pages/admin/sales/approve/[saleformId].js
  frontend/src/pages/admin/sales/index.js
  frontend/src/pages/admin/sales/register/[saleformId].js
Labels: 프론트엔드, 디자인, 수정

#131 [chore] 필터링 관련 수정 작업
  backend/src/main/java/com/woochacha/backend/domain/product/service/impl/ProductServiceImpl.java
Labels: 백엔드, 수정

#138 [Feat] 인증/인가 전체 검토&회원가입 예외처리 분리&매물 상세조회 버그 수정
  backend/src/main/java/com/woochacha/backend/config/JwtSecurityConfig.java
  backend/src/main/java/com/woochacha/backend/domain/AmazonS3/controller/AmazonS3Controller.java
  backend/src/main/java/com/woochacha/backend/domain/AmazonS3/service/AmazonS3Service.java
  backend/src/main/java/com/woochacha/backend/domain/AmazonS3/service/AmazonS3ServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/jwt/JwtAccessDeniedHandler.java
  backend/src/main/java/com/woochacha/backend/domain/jwt/JwtAuthenticationEntryPoint.java
  backend/src/main/java/com/woochacha/backend/domain/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/com/woochacha/backend/domain/jwt/JwtAuthorizationFilter.java
  backend/src/main/java/com/woochacha/backend/domain/jwt/JwtFilter.java
  backend/src/main/java/com/woochacha/backend/domain/jwt/JwtTokenProvider.java
  backend/src/main/java/com/woochacha/backend/domain/member/controller/MemberController.java
  backend/src/main/java/com/woochacha/backend/domain/member/dto/LoginResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/member/dto/SignUpRequestDto.java
  backend/src/main/java/com/woochacha/backend/domain/member/dto/SignUpResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/member/entity/Member.java
  backend/src/main/java/com/woochacha/backend/domain/member/exception/LoginException.java
  backend/src/main/java/com/woochacha/backend/domain/member/exception/SignUpException.java
  backend/src/main/java/com/woochacha/backend/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/SignService.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/impl/SignServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/impl/UserDetailsServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/product/dto/detail/ProductDetailInfo.java
  backend/src/main/java/com/woochacha/backend/domain/product/service/ProductService.java
  backend/src/main/java/com/woochacha/backend/domain/product/service/impl/ProductServiceImpl.java
  backend/src/main/java/com/woochacha/backend/security/configs/SecurityConfig.java
  package-lock.json
Labels: 버그, 기능, 리팩터링, 백엔드

#132 [design] 상세페이지 UI 레이아웃 구성
  frontend/src/components/common/BasicModal.js
  frontend/src/components/product/ImageSlider.js
  frontend/src/constants/string.js
  frontend/src/pages/product/detail/[productId].js
  frontend/src/pages/product/index.js
  frontend/src/services/productApi.js
  frontend/src/utils/date.js
Labels: 기능, 프론트엔드, 디자인

#134 [Feat] 백엔드 - 관리자 매물 등록 기능 구현
  backend/src/main/java/com/woochacha/backend/domain/AmazonS3/service/AmazonS3Service.java
  backend/src/main/java/com/woochacha/backend/domain/AmazonS3/service/AmazonS3ServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/admin/controller/ApproveSaleController.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/RegisterInputDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/RegisterProductDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/detail/RegisterProductBasicInfo.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/detail/RegisterProductDetailInfo.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/RegisterProductService.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/RegisterProductServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/car/detail/entity/CarDetail.java
  backend/src/main/java/com/woochacha/backend/domain/car/detail/entity/CarName.java
  backend/src/main/java/com/woochacha/backend/domain/car/detail/entity/CarOption.java
  backend/src/main/java/com/woochacha/backend/domain/car/detail/repository/CarDetailRepository.java
  backend/src/main/java/com/woochacha/backend/domain/car/detail/repository/CarNameRepository.java
  backend/src/main/java/com/woochacha/backend/domain/car/detail/repository/CarOptionRepository.java
  backend/src/main/java/com/woochacha/backend/domain/car/detail/repository/README.md
  backend/src/main/java/com/woochacha/backend/domain/car/info/entity/CarAccidentInfo.java
  backend/src/main/java/com/woochacha/backend/domain/car/info/entity/CarExchangeInfo.java
  backend/src/main/java/com/woochacha/backend/domain/car/info/repository/AccidentTypeRepository.java
  backend/src/main/java/com/woochacha/backend/domain/car/info/repository/CarAccidentInfoRepository.java
  backend/src/main/java/com/woochacha/backend/domain/car/info/repository/CarExchangeInfoRepository.java
  backend/src/main/java/com/woochacha/backend/domain/car/info/repository/ExchangeTypeRepository.java
  backend/src/main/java/com/woochacha/backend/domain/car/info/repository/README.md
  backend/src/main/java/com/woochacha/backend/domain/car/type/entity/Model.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/repository/ColorRepository.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/repository/FuelRepository.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/repository/ModelRepository.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/repository/README.md
  backend/src/main/java/com/woochacha/backend/domain/car/type/repository/TransmissionRepository.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/repository/TypeRepository.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/repository/MypageRepository.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/service/impl/MypageServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/product/entity/Product.java
  backend/src/main/java/com/woochacha/backend/domain/product/repository/CarImageRepository.java
  backend/src/main/java/com/woochacha/backend/domain/product/repository/ProductRepository.java
  frontend/package-lock.json
Labels: 기능, 백엔드

#135 [Feat] 백엔드 - 마이페이지 프로필 수정 구현
  backend/src/main/java/com/woochacha/backend/domain/AmazonS3/dto/AmazonS3RequestDto.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/controller/MypageController.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/dto/EditProdileDto.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/service/impl/MypageServiceImpl.java
  frontend/next.config.js
Labels: 기능, 백엔드

#141 [chore] 관리자 페이지 전체 UI 수정
  frontend/src/components/admin/MemberTable.js
  frontend/src/components/admin/ProductTable.js
  frontend/src/components/admin/PurchaseTable.js
  frontend/src/components/admin/SaleTable.js
  frontend/src/constants/string.js
  frontend/src/hooks/withAdminAuth.js
  frontend/src/layouts/DefaultFooter.js
  frontend/src/layouts/DefaultHeader.js
  frontend/src/pages/admin/members/[memberId].js/index.js
  frontend/src/pages/admin/members/[memberId]/index.js
  frontend/src/pages/admin/members/[memberId]/log.js
  frontend/src/pages/admin/members/edit/[memberId].js
  frontend/src/pages/admin/members/index.js
  frontend/src/pages/admin/product/edit/[productId].js
  frontend/src/pages/admin/product/index.js
  frontend/src/pages/admin/purchase/[purchaseId].js
  frontend/src/pages/admin/purchase/index.js
  frontend/src/pages/admin/sales/approve/[saleformId].js
  frontend/src/pages/admin/sales/index.js
  frontend/src/pages/admin/sales/register/[saleformId].js
Labels: 프론트엔드, 디자인, 수정

#137 [Feat] 백엔드 - 등록한 매물 삭제 신청 기능
  backend/src/main/java/com/woochacha/backend/domain/mypage/controller/MypageController.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/repository/MypageRepository.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/service/impl/MypageServiceImpl.java
Labels: 기능, 백엔드

#148 [chore] axios baseURL 수정
  frontend/src/utils/api.js
Labels: 프론트엔드, 수정

#149 [Feat] 관리자 매물관리 기능 구현
  backend/src/main/java/com/woochacha/backend/domain/admin/controller/ManageProductController.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/magageProduct/EditProductDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/magageProduct/ManageProductFormDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/repository/ManageProductFormRepository.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/ManageProductFormService.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/ManageProductFormServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/service/impl/MypageServiceImpl.java
Labels: 기능, 백엔드

#150 [feat] 관리자 차량 구매 관리 기능 구현
  backend/build.gradle
  backend/src/main/java/com/woochacha/backend/domain/admin/controller/ManageTransactionController.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/manageMember/PurchaseDateRequestDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/manageMember/PurchaseFormListResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/manageMember/PurchaseMemberInfoResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/sendMessage/MessageDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/sendMessage/SmsRequestDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/sendMessage/SmsResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/ManageTransactionService.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/ApproveSaleServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/ManageTransactionServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/product/repository/ProductRepository.java
  backend/src/main/java/com/woochacha/backend/domain/purchase/repository/PurchaseFormRepository.java
  backend/src/main/java/com/woochacha/backend/domain/transaction/entity/Transaction.java
  backend/src/main/java/com/woochacha/backend/domain/transaction/repository/TransactionRepository.java
Labels: 기능, 백엔드

#146 [Design] 판매자 내 차 판매 신청 폼 UI
  frontend/src/pages/product/sale.js
Labels: 프론트엔드, 디자인

#153 [Feature] 계정 정지 회원의 재회원가입 방지 기능&회원 조회 로직 리팩토링
  backend/src/main/java/com/woochacha/backend/common/CommonResponse.java
  backend/src/main/java/com/woochacha/backend/domain/member/exception/LoginException.java
  backend/src/main/java/com/woochacha/backend/domain/member/exception/SignResultCode.java
  backend/src/main/java/com/woochacha/backend/domain/member/exception/SignUpException.java
  backend/src/main/java/com/woochacha/backend/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/impl/SignServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/impl/UserDetailsServiceImpl.java
Labels: 기능, 리팩터링, 백엔드

#155 [faet] (관리자 페이지) 사용자 상세 정보 조회 기능 구현
  backend/src/main/java/com/woochacha/backend/domain/admin/controller/ManageMemberController.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/manageMember/MemberInfoDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/manageMember/MemberInfoResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/ManageMemberService.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/ManageMemberServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/woochacha/backend/domain/product/repository/ProductRepository.java
  backend/src/main/java/com/woochacha/backend/domain/purchase/controller/PurchaseController.java
  backend/src/main/java/com/woochacha/backend/domain/purchase/repository/PurchaseFormRepository.java
  backend/src/main/java/com/woochacha/backend/domain/purchase/service/PurchaseApplyService.java
  backend/src/main/java/com/woochacha/backend/domain/purchase/service/serviceImpl/PurchaseApplyServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/sale/repository/SaleFormRepository.java
  backend/src/main/java/com/woochacha/backend/domain/transaction/repository/TransactionRepository.java
Labels: 기능, 백엔드

#161 [Chore] 매물 관리 리스트에 활동 가능한 멤버의 정보만 보여주도록 수정
  backend/src/main/java/com/woochacha/backend/domain/admin/repository/ManageProductFormRepository.java
Labels: 기능, 백엔드, 수정

#162 [Feat] 백엔드 사용자 로그 관리 페이지 구현
  backend/src/main/java/com/woochacha/backend/domain/admin/controller/ManageMemberController.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/manageMember/MemberLogDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/repository/ManageProductFormRepository.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/ManageMemberService.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/ManageMemberServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/log/entity/Log.java
Labels: 기능, 백엔드

#165 [Feature]log save API 구현&로그인, 로그아웃, 구매 신청에 로그 저장 구현
  backend/src/main/java/com/woochacha/backend/domain/log/entity/Log.java
  backend/src/main/java/com/woochacha/backend/domain/log/repository/LogRepository.java
  backend/src/main/java/com/woochacha/backend/domain/log/repository/README.md
  backend/src/main/java/com/woochacha/backend/domain/log/service/LogService.java
  backend/src/main/java/com/woochacha/backend/domain/log/service/impl/LogServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/member/controller/MemberController.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/SignService.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/impl/SignServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/product/controller/ProductController.java
  backend/src/main/java/com/woochacha/backend/domain/product/dto/ProductPurchaseRequestDto.java
  backend/src/main/java/com/woochacha/backend/domain/product/service/impl/ProductServiceImpl.java
Labels: 기능, 백엔드

#166 [design] 사용자 정보 상세 페이지 구현
  frontend/src/pages/admin/members/[memberId]/index.js
Labels: 프론트엔드, 디자인

#159 [Design] 관리자 사용자 정보 상세 수정 페이지 UI
  frontend/src/pages/admin/members/edit/[memberId].js
Labels: 프론트엔드, 디자인

#169 [feature] 로그인 응답 상태에 따른 분기 처리
  frontend/src/components/auth/LoginForm.js
  frontend/src/components/auth/SignupForm.js
  frontend/src/hooks/withNoAuth.js
  frontend/src/pages/users/login.js
  frontend/src/pages/users/signup.js
  frontend/src/services/authApi.js
Labels: 기능, 프론트엔드, 수정

#170 [Feature] 토큰 검증을 통한 회원 탈퇴 승인&탈퇴 로그 기록 구현
  backend/src/main/java/com/woochacha/backend/domain/jwt/JwtAccessDeniedHandler.java
  backend/src/main/java/com/woochacha/backend/domain/jwt/JwtTokenProvider.java
  backend/src/main/java/com/woochacha/backend/domain/log/service/impl/LogServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/member/controller/MemberController.java
  backend/src/main/java/com/woochacha/backend/domain/member/dto/SignResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/member/exception/SignException.java
  backend/src/main/java/com/woochacha/backend/domain/member/exception/SignResultCode.java
  backend/src/main/java/com/woochacha/backend/domain/member/exception/SignUpException.java
  backend/src/main/java/com/woochacha/backend/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/SignService.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/impl/SignServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/impl/UserDetailsServiceImpl.java
Labels: 기능, 리팩터링, 백엔드

#172 [Chore] 오타수정
  backend/src/main/java/com/woochacha/backend/domain/mypage/controller/MypageController.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/dto/EditProfileDto.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/service/impl/MypageServiceImpl.java
Labels: 버그, 백엔드, 수정

#175 [Feature] 상품 수정, 매물 삭제, 프로필 수정, 판매 신청 로그 저장
  backend/src/main/java/com/woochacha/backend/domain/mypage/controller/MypageController.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/service/impl/MypageServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/product/controller/ProductController.java
  backend/src/main/java/com/woochacha/backend/domain/product/service/impl/ProductServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/sale/controller/SaleController.java
  backend/src/main/java/com/woochacha/backend/domain/sale/service/SaleFormApplyService.java
  backend/src/main/java/com/woochacha/backend/domain/sale/service/SaleFormApplyServiceImpl.java
  backend/src/main/java/com/woochacha/backend/security/configs/SecurityConfig.java
Labels: 기능, 백엔드

#176 [Feat] 사용자 마이페이지 Api 연결
  frontend/src/components/common/FileUpload.js
  frontend/src/components/mypage/MypageProfile.js
  frontend/src/components/mypage/MypageProfileEdit.js
  frontend/src/services/mypageApi.js
  frontend/src/services/profileApi.js
Labels: 기능, 프론트엔드

#178 [chore] Jenkins Build error : product entity car image 필드에 @Builder.Default 추가
  backend/src/main/java/com/woochacha/backend/domain/product/entity/Product.java
Labels: 버그, 인프라

#182 [bug] 구매 신청 이력 조회 반환 데이터 형식 수정
  backend/src/main/java/com/woochacha/backend/domain/mypage/controller/MypageController.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/dto/PurchaseReqeustListDto.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/repository/MypageRepository.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/service/impl/MypageServiceImpl.java
  backend/src/main/java/com/woochacha/backend/security/configs/SecurityConfig.java
Labels: 버그, 백엔드, 수정

#186 [chore] : 관리자가 변경하는 사용자의 상태의 변수 명 수정
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/manageMember/EditMemberRequestDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/ManageMemberServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/member/repository/MemberRepository.java
Labels: 백엔드, 수정

#187 [feat] 관리자페이지 - 사용자 관리 목록 조회 및 정보 상세 페이지 API 연동
  frontend/src/components/admin/MemberTable.js
  frontend/src/pages/admin/members/[memberId]/index.js
  frontend/src/pages/admin/members/edit/[memberId].js
  frontend/src/pages/admin/members/index.js
  frontend/src/services/adminpageApi.js
Labels: 기능, 프론트엔드

#190 [feature] 관리자페이지 - 사용자 매물 관리 목록 조회 / 삭제 신청 / 수정 신청 API 연동
  frontend/src/components/admin/ProductTable.js
  frontend/src/components/common/ApproveModal.js
  frontend/src/constants/string.js
  frontend/src/pages/admin/product/index.js
  frontend/src/services/adminpageApi.js
Labels: 기능, 프론트엔드, 수정

#192 [feat] 차량 조회 부분 api 통신 구현
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/approve/ApproveSaleResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/ApproveSaleServiceImpl.java
  frontend/package-lock.json
  frontend/src/components/product/ImageSlider.js
  frontend/src/components/product/SearchBar.js
  frontend/src/constants/string.js
  frontend/src/pages/product/detail/[productId].js
  frontend/src/pages/product/index.js
  frontend/src/services/productApi.js
Labels: 기능, 프론트엔드, 백엔드, 수정

#194 [Feat] 마이페이지 상품 수정, 삭제 신청 API 연결
  backend/src/main/java/com/woochacha/backend/domain/mypage/controller/MypageController.java
  backend/src/main/java/com/woochacha/backend/security/configs/SecurityConfig.java
  frontend/src/components/mypage/MypageCardEdit.js
  frontend/src/components/mypage/MypageProfileEdit.js
  frontend/src/constants/string.js
  frontend/src/pages/mypage/registered/[userId].js
  frontend/src/pages/mypage/registered/edit.js
  frontend/src/services/mypageApi.js
Labels: 기능, 프론트엔드

#196 [feature] 관리자페이지 - 판매 신청 관리 목록, 판매 승인, 판매 게시글 등록 API 연동
  frontend/src/components/admin/SaleTable.js
  frontend/src/pages/admin/sales/approve/[saleformId].js
  frontend/src/pages/admin/sales/index.js
  frontend/src/services/adminpageApi.js
Labels: 기능, 프론트엔드

#198 [chore] 프론트에서 api 요청 중 필요한 기능 추가 수정
  backend/src/main/java/com/woochacha/backend/domain/admin/controller/ApproveSaleController.java
  backend/src/main/java/com/woochacha/backend/domain/admin/controller/ManageMemberController.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/approve/CarInspectionInfoResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/ApproveSaleService.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/ApproveSaleServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/sale/controller/SaleController.java
  backend/src/main/java/com/woochacha/backend/domain/sale/repository/SaleFormRepository.java
Labels: 기능, 백엔드, 수정

#201 [feat] 판매 신청 폼의 api 요청 구현
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/manageMember/PurchaseFormListResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/ManageTransactionServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/product/repository/ProductRepository.java
  backend/src/main/java/com/woochacha/backend/domain/sale/controller/SaleController.java
  backend/src/main/java/com/woochacha/backend/domain/sale/service/SaleFormApplyService.java
  backend/src/main/java/com/woochacha/backend/domain/sale/service/SaleFormApplyServiceImpl.java
  frontend/src/pages/product/sale.js
  frontend/src/services/productApi.js
Labels: 기능, 프론트엔드, 백엔드, 수정

#203 [feature] 관리자페이지 - 거래 관리 페이지 API 연동
  frontend/src/components/admin/PurchaseTable.js
  frontend/src/pages/admin/purchase/index.js
  frontend/src/services/adminpageApi.js
Labels: 기능, 프론트엔드, 수정

#202 [Test] Product Controller 단위 테스트 코드 작성
  backend/build.gradle
  backend/src/main/java/com/woochacha/backend/domain/product/dto/all/ProductInfo.java
  backend/src/main/java/com/woochacha/backend/domain/product/dto/detail/ProductAccidentInfo.java
  backend/src/main/java/com/woochacha/backend/domain/product/dto/detail/ProductBasicInfo.java
  backend/src/main/java/com/woochacha/backend/domain/product/dto/detail/ProductDetailInfo.java
  backend/src/main/java/com/woochacha/backend/domain/product/dto/detail/ProductExchangeInfo.java
  backend/src/main/java/com/woochacha/backend/domain/product/dto/detail/ProductOptionInfo.java
  backend/src/main/java/com/woochacha/backend/domain/product/dto/detail/ProductOwnerInfo.java
  backend/src/main/java/com/woochacha/backend/domain/product/dto/filter/ProductFilterInfo.java
  backend/src/main/java/com/woochacha/backend/domain/product/entity/Product.java
  backend/src/main/java/com/woochacha/backend/domain/product/service/impl/ProductServiceImpl.java
  backend/src/main/java/com/woochacha/backend/security/configs/SecurityConfig.java
  backend/src/test/java/com/woochacha/backend/domain/product/controller/ProductControllerTest.java
Labels: 백엔드, 테스트

#205 [Chore] 매물 로그 저장 수정&접속 권한 수정
  backend/src/main/java/com/woochacha/backend/domain/mypage/service/impl/MypageServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/product/service/impl/ProductServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/sale/service/SaleFormApplyServiceImpl.java
  backend/src/main/java/com/woochacha/backend/security/configs/SecurityConfig.java
  frontend/src/services/productApi.js
Labels: 버그, 백엔드, 수정

#209 [feature] 관리자페이지 - 판매 신청 관리 목록, 판매 승인, 판매 게시글 등록 API 연동
  frontend/src/components/common/MultipleFileUpload.js
  frontend/src/components/mypage/MypageProfileEdit.js
  frontend/src/constants/regExp.js
  frontend/src/constants/string.js
  frontend/src/pages/admin/sales/approve/[saleformId].js
  frontend/src/pages/admin/sales/index.js
  frontend/src/pages/admin/sales/register/[saleformId].js
  frontend/src/services/adminpageApi.js
  frontend/src/services/profileApi.js
  frontend/src/utils/api.js
Labels: 기능, 프론트엔드, 수정

#208 [Bug] 마이페이지 api 오류 수정
  backend/src/main/java/com/woochacha/backend/domain/mypage/dto/MemberIdDto.java
  frontend/src/components/mypage/MypageCard.js
  frontend/src/components/mypage/MypageCardEdit.js
  frontend/src/components/mypage/MypageCardPurchase.js
  frontend/src/services/mypageApi.js
Labels: 버그, 수정

#210 [feat] db 이중화 구현
  backend/src/main/java/com/woochacha/backend/common/DataSourceType.java
  backend/src/main/java/com/woochacha/backend/config/dataSourceReplication/DataSourceConfig.java
  backend/src/main/java/com/woochacha/backend/config/dataSourceReplication/RoutingDataSource.java
  backend/src/main/java/com/woochacha/backend/config/dataSourceReplication/RoutingDataSourceConfig.java
  backend/src/main/java/com/woochacha/backend/domain/admin/controller/ApproveSaleController.java
  backend/src/main/java/com/woochacha/backend/domain/car/detail/entity/CarDetail.java
  backend/src/main/java/com/woochacha/backend/domain/car/detail/entity/CarName.java
  backend/src/main/java/com/woochacha/backend/domain/car/detail/entity/CarOption.java
  backend/src/main/java/com/woochacha/backend/domain/car/info/entity/AccidentType.java
  backend/src/main/java/com/woochacha/backend/domain/car/info/entity/CarAccidentInfo.java
  backend/src/main/java/com/woochacha/backend/domain/car/info/entity/CarExchangeInfo.java
  backend/src/main/java/com/woochacha/backend/domain/car/info/entity/ExchangeType.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/entity/Color.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/entity/Fuel.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/entity/Model.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/entity/Transmission.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/entity/Type.java
  backend/src/main/java/com/woochacha/backend/domain/log/entity/Log.java
  backend/src/main/java/com/woochacha/backend/domain/member/entity/Member.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/controller/MypageController.java
  backend/src/main/java/com/woochacha/backend/domain/product/entity/CarImage.java
  backend/src/main/java/com/woochacha/backend/domain/product/entity/Product.java
  backend/src/main/java/com/woochacha/backend/domain/purchase/entity/PurchaseForm.java
  backend/src/main/java/com/woochacha/backend/domain/sale/entity/Branch.java
  backend/src/main/java/com/woochacha/backend/domain/sale/entity/SaleForm.java
  backend/src/main/java/com/woochacha/backend/domain/status/entity/CarStatus.java
  backend/src/main/java/com/woochacha/backend/domain/transaction/entity/Transaction.java
Labels: 기능, 백엔드, 수정

#213 [feat] alert창 커스텀화
  backend/src/main/java/com/woochacha/backend/domain/mypage/dto/MemberIdDto.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/mypage/MypageProfileEdit.js
  frontend/src/utils/api.js
Labels: 기능, 프론트엔드, 수정

#215 [feature] 상품 필터링 API 기능 연동
  frontend/src/components/product/FilterSideBar.js
  frontend/src/components/product/MultipleSelect.js
  frontend/src/pages/index.js
  frontend/src/pages/product/index.js
  frontend/src/services/productApi.js
Labels: 기능, 프론트엔드, 수정

#217 [Chore] frelList 사용하는 부분 enum에서 string으로 변경
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/RegisterProductServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/repository/FuelRepository.java
Labels: 백엔드, 수정

#219 [Test] Product 테스트 코드에 Rest Docs 적용
  backend/build.gradle
  backend/src/docs/asciidoc/Product.adoc
  backend/src/main/java/com/woochacha/backend/domain/car/detail/dto/CarNameDto.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/dto/ColorDto.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/dto/FuelDto.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/dto/ModelDto.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/dto/TransmissionDto.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/dto/TypeDto.java
  backend/src/main/java/com/woochacha/backend/domain/sale/dto/BranchDto.java
  backend/src/main/resources/static/docs/Product.html
  backend/src/test/java/com/woochacha/backend/domain/product/controller/ProductControllerTest.java
Labels: 문서 작성, 백엔드, 테스트

#222 [chore] UI 수정 및 프론트 유효성 검사 추가
  frontend/src/components/admin/AdminpageSidebar.js
  frontend/src/components/common/MenuAppbar.js
  frontend/src/components/common/ProfileAppbar.js
  frontend/src/components/common/SubTabMenu.js
  frontend/src/components/mypage/MypageSidebar.js
  frontend/src/constants/string.js
  frontend/src/layouts/DefaultFooter.js
  frontend/src/layouts/DefaultHeader.js
  frontend/src/pages/mypage/purchase-request/[userId].js
  frontend/src/pages/mypage/purchase/[userId].js
  frontend/src/pages/mypage/sale-request/[userId].js
  frontend/src/pages/mypage/sale/[userId].js
  frontend/src/services/authApi.js
  frontend/src/utils/modal.js
Labels: 기능, 프론트엔드, 디자인, 수정

#223 [Chore] QLDB exchange info 필드명 수정&프론트엔드 리다이렉트 경로 수정
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/approve/CarAccidentInfoDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/approve/CarExchangeInfoDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/approve/CompareRequestDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/ApproveSaleServiceImpl.java
  backend/src/test/java/com/woochacha/backend/domain/common/CommonTest.java
  backend/src/test/java/com/woochacha/backend/domain/product/controller/ProductControllerTest.java
  frontend/src/pages/index.js
Labels: 버그, 프론트엔드, 백엔드

#225 [chore] qldb 옵션명 수정, fuelList 삭제
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/RegisterProductServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/entity/Fuel.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/entity/FuelList.java
  backend/src/main/java/com/woochacha/backend/domain/car/type/repository/FuelRepository.java
  backend/src/test/java/com/woochacha/backend/domain/common/CommonTest.java
  backend/src/test/java/com/woochacha/backend/domain/member/controller/MemberControllerTest.java
  backend/src/test/java/com/woochacha/backend/domain/product/controller/ProductControllerTest.java
Labels: 버그, 백엔드, 수정

#226 [chore] @Builder 사용하는 DTO 생성자 작성
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/approve/ApproveSaleResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/approve/CarAccidentInfoDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/approve/CarExchangeInfoDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/approve/CarInspectionInfoResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/approve/CompareRequestDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/approve/RegisterProductDto.java
Labels: 공부, 백엔드, 수정

#229 [Test] Member 테스트 코드 작성 및 Rest docs 적용&Rest Docs 모듈화
  backend/src/docs/asciidoc/Member.adoc
  backend/src/docs/asciidoc/Product.adoc
  backend/src/docs/asciidoc/Woochacha.adoc
  backend/src/docs/asciidoc/src/docs/asciidoc/Product.adoc
  backend/src/main/java/com/woochacha/backend/domain/member/dto/LoginRequestDto.java
  backend/src/main/java/com/woochacha/backend/domain/member/dto/LoginResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/member/dto/SignResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/member/dto/SignUpRequestDto.java
  backend/src/main/resources/static/docs/Woochacha.html
  backend/src/test/java/com/woochacha/backend/domain/member/controller/MemberControllerTest.java
  backend/src/test/java/com/woochacha/backend/domain/product/controller/ProductControllerTest.java
Labels: 리팩터링, 백엔드, 테스트

#230 [Feature] 유효성 처리 및 수정
  frontend/src/components/auth/LoginForm.js
  frontend/src/components/auth/SignupForm.js
  frontend/src/components/common/MultipleFileUpload.js
  frontend/src/components/mypage/MypageCardEdit.js
  frontend/src/hooks/useChecks.js
  frontend/src/pages/admin/sales/register/[saleformId].js
  frontend/src/pages/product/sale.js
  frontend/src/services/mypageApi.js
  frontend/src/utils/api.js
  frontend/src/utils/modal.js
  frontend/src/utils/validate.js
Labels: 기능, 프론트엔드, 수정

#232 [bug] 회원가입 관련 버그 수정
  frontend/src/components/auth/SignupForm.js
Labels: 버그, 프론트엔드, 수정

#235 [chore] Mixed Content 관련 meta 태그 추가
  frontend/src/pages/_document.js
  frontend/src/utils/api.js
Labels: 인프라, 프론트엔드, 수정

#237 [chore] "/product/{productId}" post 빌더 수정
  backend/src/test/java/com/woochacha/backend/domain/product/controller/ProductControllerTest.java
Labels: 버그, 백엔드, 테스트

#240 [chore] api base uri 수정
  frontend/src/pages/index.js
  frontend/src/pages/product/index.js
Labels: 버그, 프론트엔드, 수정

#238 [Bug] 매물 등록 시 사고, 교체이력 입력 안했을 때 나오는 500에러 해결
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/RegisterProductServiceImpl.java
Labels: 버그, 백엔드, 수정

#244 [Feature] 로그인 한 회원의 토큰이 만료되었을 경우, 만료된 토큰이라는 메시지 전달
  backend/src/main/java/com/woochacha/backend/domain/jwt/JwtAuthenticationEntryPoint.java
  backend/src/main/java/com/woochacha/backend/domain/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/com/woochacha/backend/domain/jwt/JwtFilter.java
  backend/src/main/java/com/woochacha/backend/domain/jwt/JwtTokenProvider.java
Labels: 기능, 리팩터링, 백엔드

#248 [Bug] 차량 매물 등록시 사고, 교체이력 데이터 중복 해결
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/RegisterProductServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/product/service/impl/ProductServiceImpl.java
Labels: 버그, 백엔드, 수정

#250 [Test] MyPage 테스트 코드 작성, Rest Docs 적용, 기타
  backend/src/docs/asciidoc/Member.adoc
  backend/src/docs/asciidoc/MyPage.adoc
  backend/src/docs/asciidoc/Product.adoc
  backend/src/docs/asciidoc/Woochacha.adoc
  backend/src/docs/asciidoc/src/docs/asciidoc/Product.adoc
  backend/src/main/java/com/woochacha/backend/domain/AmazonS3/dto/AmazonS3RequestDto.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/controller/MypageController.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/dto/EditProductDto.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/dto/ProfileDto.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/dto/SaleFormDto.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/dto/UpdatePriceDto.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/service/MypageService.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/service/impl/MypageServiceImpl.java
  backend/src/main/resources/static/docs/Woochacha.html
  backend/src/test/java/com/woochacha/backend/common/user.jpeg
  backend/src/test/java/com/woochacha/backend/domain/mypage/controller/MypageControllerTest.java
  backend/src/test/java/com/woochacha/backend/domain/product/controller/ProductControllerTest.java
Labels: 리팩터링, 백엔드, 수정, 테스트

#252 [feature] 유효성 처리 및 수정
  frontend/src/components/admin/AdminpageSidebar.js
  frontend/src/components/admin/MemberTable.js
  frontend/src/components/admin/ProductTable.js
  frontend/src/components/admin/PurchaseTable.js
  frontend/src/components/admin/SaleTable.js
  frontend/src/components/common/ProfileAppbar.js
  frontend/src/components/common/SubTabMenu.js
  frontend/src/components/mypage/MypageCardPurchase.js
  frontend/src/components/mypage/MypageProfile.js
  frontend/src/components/mypage/MypageProfileEdit.js
  frontend/src/components/mypage/MypageSidebar.js
  frontend/src/constants/string.js
  frontend/src/layouts/admin/AdminPageLayout.js
  frontend/src/layouts/user/UserMyPageLayout.js
  frontend/src/pages/_document.js
  frontend/src/pages/admin/members/[memberId]/index.js
  frontend/src/pages/admin/members/edit/[memberId].js
  frontend/src/pages/admin/members/index.js
  frontend/src/pages/admin/members/log/[memberId].js
  frontend/src/pages/admin/product/edit/[productId].js
  frontend/src/pages/admin/product/index.js
  frontend/src/pages/admin/purchase/[purchaseId].js
  frontend/src/pages/admin/purchase/index.js
  frontend/src/pages/admin/sales/approve/[saleformId].js
  frontend/src/pages/admin/sales/index.js
  frontend/src/pages/admin/sales/register/[saleformId].js
  frontend/src/pages/capitals/index.js
  frontend/src/pages/index.js
  frontend/src/pages/mypage/[userId].js
  frontend/src/pages/mypage/profile/edit/[userId].js
  frontend/src/pages/mypage/purchase-request/[userId].js
  frontend/src/pages/mypage/purchase/[userId].js
  frontend/src/pages/mypage/registered/[userId].js
  frontend/src/pages/mypage/registered/edit.js
  frontend/src/pages/mypage/sale-request/[userId].js
  frontend/src/pages/mypage/sale/[userId].js
  frontend/src/pages/product/detail/[productId].js
  frontend/src/pages/product/index.js
  frontend/src/pages/product/sale.js
  frontend/src/services/adminpageApi.js
  frontend/src/services/authApi.js
  frontend/src/services/mypageApi.js
  frontend/src/services/productApi.js
  frontend/src/utils/api.js
Labels: 기능, 프론트엔드, 수정

#253 [Feature] product get all 페이지네이션 적용
  backend/src/main/java/com/woochacha/backend/config/WebConfig.java
  backend/src/main/java/com/woochacha/backend/domain/product/controller/ProductController.java
  backend/src/main/java/com/woochacha/backend/domain/product/dto/ProductAllResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/product/service/ProductService.java
  backend/src/main/java/com/woochacha/backend/domain/product/service/impl/ProductServiceImpl.java
  backend/src/main/resources/static/docs/Woochacha.html
  backend/src/test/java/com/woochacha/backend/domain/common/CommonTest.java
  backend/src/test/java/com/woochacha/backend/domain/product/controller/ProductControllerTest.java
Labels: 기능, 백엔드, 테스트

#255 [Test] GET /admin/sales 리팩토링&테스트 코드 구현 및 Rest Docs 적용
  backend/src/main/java/com/woochacha/backend/domain/admin/controller/ApproveSaleController.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/ApproveSaleService.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/ApproveSaleServiceImpl.java
  backend/src/test/java/com/woochacha/backend/domain/admin/controller/ApproveSaleControllerTest.java
Labels: 리팩터링, 백엔드, 테스트

#256 [fix] 필터링 관련 에러 수정
  frontend/src/pages/product/index.js
Labels: 버그, 프론트엔드, 수정

#264 [Test] ManageProductController 테스트 코드 작성&Rest Docs 적용&admin/user adoc 파일 폴더구조 변경
  backend/src/docs/asciidoc/admin/ManageProduct.adoc
  backend/src/docs/asciidoc/admin/Woochacha-admin.adoc
  backend/src/docs/asciidoc/user/Member.adoc
  backend/src/docs/asciidoc/user/MyPage.adoc
  backend/src/docs/asciidoc/user/Product.adoc
  backend/src/docs/asciidoc/user/Woochacha-user.adoc
  backend/src/main/java/com/woochacha/backend/domain/admin/controller/ManageProductController.java
  backend/src/test/java/com/woochacha/backend/domain/admin/controller/ManageProductControllerTest.java
Labels: 백엔드, 테스트

#265 [Test] manage transaction 테스트 코드 작성&Rest Docs 적용
  backend/build.gradle
  backend/src/docs/asciidoc/admin/ManageProduct.adoc
  backend/src/docs/asciidoc/admin/ManagePurchase.adoc
  backend/src/docs/asciidoc/admin/Woochacha-admin.adoc
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/manageMember/PurchaseDateRequestDto.java
  backend/src/test/java/com/woochacha/backend/domain/admin/controller/ManageProductControllerTest.java
  backend/src/test/java/com/woochacha/backend/domain/admin/controller/ManageTransactionControllerTest.java
Labels: 리팩터링, 백엔드, 테스트

#266 [Test] SaleController 테스트코드 구현&Rest Docs 적용
  backend/src/docs/asciidoc/user/Sale.adoc
  backend/src/docs/asciidoc/user/Woochacha-user.adoc
  backend/src/main/java/com/woochacha/backend/domain/sale/controller/SaleController.java
  backend/src/test/java/com/woochacha/backend/domain/sale/controller/SaleControllerTest.java
Labels: 백엔드, 테스트

#267 [feat] product 페이지네이션 처리
  frontend/src/components/product/ProductCard.js
  frontend/src/pages/index.js
  frontend/src/pages/product/index.js
  frontend/src/services/productApi.js
Labels: 기능, 프론트엔드

#271 [Chore] 전역 예외처리 설정
  backend/src/main/java/com/woochacha/backend/domain/admin/controller/ApproveSaleController.java
  backend/src/main/java/com/woochacha/backend/domain/admin/exception/AdminForbidden.java
  backend/src/main/java/com/woochacha/backend/domain/admin/exception/AdminNotAuth.java
  backend/src/main/java/com/woochacha/backend/domain/admin/exception/AdminNotFound.java
  backend/src/main/java/com/woochacha/backend/domain/car/detail/controller/README.md
  backend/src/main/java/com/woochacha/backend/domain/car/detail/exception/README.md
  backend/src/main/java/com/woochacha/backend/domain/car/detail/service/README.md
  backend/src/main/java/com/woochacha/backend/domain/car/exception/CarNotFound.java
  backend/src/main/java/com/woochacha/backend/domain/car/info/controller/README.md
  backend/src/main/java/com/woochacha/backend/domain/car/info/dto/README.md
  backend/src/main/java/com/woochacha/backend/domain/car/info/exception/README.md
  backend/src/main/java/com/woochacha/backend/domain/car/info/service/README.md
  backend/src/main/java/com/woochacha/backend/domain/car/type/controller/README.md
  backend/src/main/java/com/woochacha/backend/domain/car/type/exception/README.md
  backend/src/main/java/com/woochacha/backend/domain/car/type/service/README.md
  backend/src/main/java/com/woochacha/backend/domain/log/controller/README.md
  backend/src/main/java/com/woochacha/backend/domain/log/dto/README.md
  backend/src/main/java/com/woochacha/backend/domain/log/exception/LogNotFound.java
  backend/src/main/java/com/woochacha/backend/domain/log/exception/README.md
  backend/src/main/java/com/woochacha/backend/domain/log/service/README.md
  backend/src/main/java/com/woochacha/backend/domain/member/controller/MemberController.java
  backend/src/main/java/com/woochacha/backend/domain/member/exception/MemberNotFound.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/exception/MypageNotFound.java
  backend/src/main/java/com/woochacha/backend/domain/product/exception/ProductNotFound.java
  backend/src/main/java/com/woochacha/backend/domain/product/exception/README.md
  backend/src/main/java/com/woochacha/backend/domain/purchase/exception/PurchaseNotFound.java
  backend/src/main/java/com/woochacha/backend/domain/sale/exception/SaleFormNotFound.java
  backend/src/main/java/com/woochacha/backend/domain/status/controller/README.md
  backend/src/main/java/com/woochacha/backend/domain/status/dto/README.md
  backend/src/main/java/com/woochacha/backend/domain/status/exception/README.md
  backend/src/main/java/com/woochacha/backend/domain/status/exception/StatusNotFound.java
  backend/src/main/java/com/woochacha/backend/domain/status/repository/README.md
  backend/src/main/java/com/woochacha/backend/domain/status/service/README.md
  backend/src/main/java/com/woochacha/backend/domain/transaction/controller/README.md
  backend/src/main/java/com/woochacha/backend/domain/transaction/dto/README.md
  backend/src/main/java/com/woochacha/backend/domain/transaction/exception/README.md
  backend/src/main/java/com/woochacha/backend/domain/transaction/exception/TransactionNotFound.java
  backend/src/main/java/com/woochacha/backend/domain/transaction/repository/README.md
  backend/src/main/java/com/woochacha/backend/domain/transaction/service/README.md
  backend/src/main/java/com/woochacha/backend/exception/errorcode/CommonErrorCode.java
  backend/src/main/java/com/woochacha/backend/exception/errorcode/CustomErrorCode.java
  backend/src/main/java/com/woochacha/backend/exception/errorcode/ErrorCode.java
  backend/src/main/java/com/woochacha/backend/exception/exception/RestApiException.java
  backend/src/main/java/com/woochacha/backend/exception/handler/GlobalExceptionHandler.java
  backend/src/main/java/com/woochacha/backend/exception/response/ErrorResponse.java
Labels: 기능, 백엔드, 수정

#269 [feature] 관리자 table 페이징 처리 기능 구현
  frontend/src/components/admin/MemberTable.js
  frontend/src/components/admin/ProductTable.js
  frontend/src/components/admin/PurchaseTable.js
  frontend/src/components/admin/SaleTable.js
  frontend/src/pages/admin/members/index.js
  frontend/src/pages/admin/members/log/[memberId].js
  frontend/src/pages/admin/product/index.js
  frontend/src/pages/admin/purchase/index.js
  frontend/src/pages/admin/sales/index.js
  frontend/src/services/adminpageApi.js
  frontend/src/utils/api.js
Labels: 기능, 프론트엔드, 수정

#274 [Feature] 매물 필터링 검색, 키워드 검색 페이지네이션 적용
  backend/src/main/java/com/woochacha/backend/domain/product/controller/ProductController.java
  backend/src/main/java/com/woochacha/backend/domain/product/service/ProductService.java
  backend/src/main/java/com/woochacha/backend/domain/product/service/impl/ProductServiceImpl.java
  backend/src/test/java/com/woochacha/backend/domain/product/controller/ProductControllerTest.java
Labels: 기능, 백엔드, 테스트

#277 [feat] 페이지네이션 API 연동
  frontend/src/pages/index.js
  frontend/src/pages/mypage/profile/edit/[userId].js
  frontend/src/pages/mypage/purchase-request/[userId].js
  frontend/src/pages/mypage/purchase/[userId].js
  frontend/src/pages/mypage/registered/[userId].js
  frontend/src/pages/mypage/sale-request/[userId].js
  frontend/src/pages/mypage/sale/[userId].js
  frontend/src/pages/product/index.js
  frontend/src/services/mypageApi.js
Labels: 기능, 프론트엔드, 수정

#278 [Bug] 매물 필터링 및 키워드 검색 API에서 totalElements 불일치 해결
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/ApproveSaleServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/product/controller/ProductController.java
  backend/src/main/java/com/woochacha/backend/domain/product/dto/ProductAllResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/product/service/ProductService.java
  backend/src/main/java/com/woochacha/backend/domain/product/service/impl/ProductServiceImpl.java
  backend/src/test/java/com/woochacha/backend/domain/admin/controller/ApproveSaleControllerTest.java
  backend/src/test/java/com/woochacha/backend/domain/product/controller/ProductControllerTest.java
Labels: 버그, 테스트

#281 [test] 관리자 승인 페이지 test코드 작성
  backend/src/docs/asciidoc/admin/ApproveSaleForm.adoc
  backend/src/docs/asciidoc/admin/Woochacha-admin.adoc
  backend/src/main/java/com/woochacha/backend/domain/admin/controller/ApproveSaleController.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/ApproveSaleService.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/ApproveSaleServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/car/info/entity/ExchangeType.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/repository/MypageRepository.java
  backend/src/main/resources/static/docs/Woochacha-admin.html
  backend/src/test/java/com/woochacha/backend/domain/admin/controller/ApproveSaleControllerTest.java
  frontend/src/components/mypage/MypageCardEdit.js
  frontend/src/pages/admin/members/[memberId]/index.js
  frontend/src/pages/admin/members/edit/[memberId].js
  frontend/src/pages/admin/product/edit/[productId].js
  frontend/src/pages/admin/product/index.js
  frontend/src/pages/admin/purchase/index.js
  frontend/src/pages/admin/sales/approve/[saleformId].js
  frontend/src/pages/admin/sales/index.js
  frontend/src/pages/admin/sales/register/[saleformId].js
  frontend/src/pages/mypage/registered/edit.js
  frontend/src/pages/product/detail/[productId].js
  frontend/src/pages/product/index.js
  frontend/src/utils/api.js
Labels: 백엔드, 수정, 테스트

#283 [fix] api 연결 오류
  frontend/src/pages/index.js
  frontend/src/pages/product/index.js
  frontend/src/utils/api.js
Labels: 버그, 수정

#284 fix: cors 해결
  frontend/next.config.js
Labels: 버그, 인프라, 수정

#285 [Bug] Security Config url 추가
  backend/src/docs/asciidoc/admin/Woochacha-admin.html
  backend/src/main/java/com/woochacha/backend/domain/jwt/JwtTokenProvider.java
  backend/src/main/java/com/woochacha/backend/domain/product/service/impl/ProductServiceImpl.java
  backend/src/main/java/com/woochacha/backend/exception/errorcode/CustomErrorCode.java
  backend/src/main/java/com/woochacha/backend/exception/handler/GlobalExceptionHandler.java
  backend/src/main/java/com/woochacha/backend/security/configs/SecurityConfig.java
Labels: 버그, 백엔드

#288 [Feat] 로그 코드 추가, 예외처리 일부 추가
  backend/src/main/java/com/woochacha/backend/domain/AmazonS3/service/AmazonS3ServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/admin/exception/CrudDataFromQLDBError.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/ApproveSaleServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/ManageMemberServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/ManageProductFormServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/ManageTransactionServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/RegisterProductServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/impl/SignServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/service/impl/MypageServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/product/service/impl/ProductServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/sale/service/SaleFormApplyServiceImpl.java
  backend/src/main/java/com/woochacha/backend/exception/errorcode/CustomErrorCode.java
Labels: 에러 처리, 백엔드

#292 [Feature] 매물 키워드 검색 로직 변경&REST Docs security 권한 설정
  backend/src/main/java/com/woochacha/backend/domain/product/service/impl/ProductServiceImpl.java
  backend/src/main/java/com/woochacha/backend/security/configs/SecurityConfig.java
Labels: 기능, 백엔드, 수정

#290 [Test] ManageMember 테스트 코드 작성 및 Rest Docs 적용&최종 HTML 파일 생성
  backend/src/docs/asciidoc/admin/ApproveSaleForm.adoc
  backend/src/docs/asciidoc/admin/ManageMember.adoc
  backend/src/docs/asciidoc/admin/ManageProduct.adoc
  backend/src/docs/asciidoc/admin/ManagePurchase.adoc
  backend/src/docs/asciidoc/admin/Woochacha-admin.adoc
  backend/src/docs/asciidoc/admin/Woochacha-admin.html
  backend/src/docs/asciidoc/user/Member.adoc
  backend/src/docs/asciidoc/user/MyPage.adoc
  backend/src/docs/asciidoc/user/Product.adoc
  backend/src/main/java/com/woochacha/backend/domain/admin/controller/ManageMemberController.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/manageMember/EditMemberRequestDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/manageMember/MemberLogDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/ManageMemberService.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/ManageMemberServiceImpl.java
  backend/src/main/resources/static/docs/Woochacha-admin.html
  backend/src/main/resources/static/docs/Woochacha-user.html
  backend/src/test/java/com/woochacha/backend/domain/admin/controller/ApproveSaleControllerTest.java
  backend/src/test/java/com/woochacha/backend/domain/admin/controller/ManageMemberControllerTest.java
Labels: 백엔드, 수정, 테스트

#295 [Chore] ManageMemberControllerTest edit, delete document 폴더 경로 수정
  backend/src/test/java/com/woochacha/backend/domain/admin/controller/ManageMemberControllerTest.java
Labels: 수정, 테스트

#298 [Design] 구매 페이지 UI 수정
  frontend/src/components/common/ProfileAppbar.js
  frontend/src/components/product/ProductCard.js
  frontend/src/components/product/SearchBar.js
  frontend/src/components/product/SearchBar.module.css
  frontend/src/layouts/DefaultHeader.js
  frontend/src/pages/index.js
  frontend/src/pages/main.module.css
  frontend/src/pages/product/index.js
  frontend/src/pages/product/product.module.css
Labels: 프론트엔드, 디자인, 수정

#307 [feat] 회원가입을 위한 핸드폰 인증 기능 구현
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/ManageTransactionServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/member/controller/MemberController.java
  backend/src/main/java/com/woochacha/backend/domain/member/dto/AuthPhoneRequestDto.java
  backend/src/main/java/com/woochacha/backend/domain/member/dto/PhoneRequestDto.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/SignService.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/impl/SignServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/sendSMS/SendSmsService.java
  backend/src/main/java/com/woochacha/backend/domain/sendSMS/SendSmsServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/sendSMS/entity/AuthPhone.java
  backend/src/main/java/com/woochacha/backend/domain/sendSMS/repository/AuthPhoneRepository.java
  backend/src/main/java/com/woochacha/backend/domain/sendSMS/sendMessage/MessageDto.java
  backend/src/main/java/com/woochacha/backend/domain/sendSMS/sendMessage/SmsRequestDto.java
  backend/src/main/java/com/woochacha/backend/domain/sendSMS/sendMessage/SmsResponseDto.java
  backend/src/main/java/com/woochacha/backend/security/configs/SecurityConfig.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/auth/SignupForm.js
  frontend/src/hooks/useChecks.js
  frontend/src/pages/product/index.js
  frontend/src/services/authApi.js
Labels: 버그, 기능, 프론트엔드, 백엔드, 디자인, 수정

#312 [Feature] member email, phone 암호화, 복호화 구현
  backend/src/main/java/com/woochacha/backend/common/DataMasking.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/impl/SignServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/dto/ProfileDto.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/service/impl/MypageServiceImpl.java
  backend/src/main/java/com/woochacha/backend/security/configs/SecurityConfig.java
Labels: 기능, 백엔드

#313 [Feature] 중복 회원가입 방지 로직에 암호화 기능 구현&비암호화의 복호화 방지 기능 구현
  backend/src/main/java/com/woochacha/backend/common/DataMasking.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/impl/SignServiceImpl.java
Labels: 기능, 리팩터링, 백엔드

#318 [Test] gradlew build 후 jar 파일 실행하여 rest docs 파일에 접근하도록 작성
  backend/build.gradle
  backend/src/docs/asciidoc/admin.adoc
  backend/src/docs/asciidoc/admin/ApproveSaleForm.adoc
  backend/src/docs/asciidoc/admin/ManageMember.adoc
  backend/src/docs/asciidoc/admin/ManageProduct.adoc
  backend/src/docs/asciidoc/admin/ManagePurchase.adoc
  backend/src/docs/asciidoc/admin/Woochacha-admin.adoc
  backend/src/docs/asciidoc/user.adoc
  backend/src/docs/asciidoc/user/Member.adoc
  backend/src/docs/asciidoc/user/Product.adoc
  backend/src/docs/asciidoc/user/Sale.adoc
  backend/src/docs/asciidoc/user/Woochacha-user.adoc
  backend/src/main/java/com/woochacha/backend/common/DataMasking.java
  backend/src/main/java/com/woochacha/backend/security/configs/SecurityConfig.java
  backend/src/main/resources/static/docs/admin.html
  backend/src/main/resources/static/docs/user.html
Labels: 백엔드, 수정

#314 [hackathon] 무한 클릭에 따른 중복 요청 방지
  frontend/src/components/auth/SignupForm.js
  frontend/src/components/mypage/MypageProfile.js
  frontend/src/components/mypage/MypageProfileEdit.js
  frontend/src/components/product/ProductCard.js
  frontend/src/pages/mypage/registered/edit.js
  frontend/src/pages/product/index.js
Labels: 에러 처리, 프론트엔드, 수정

#315 [Feature] 비복호화 조건절에 조건 추가
  backend/src/main/java/com/woochacha/backend/common/DataMasking.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/impl/SignServiceImpl.java
Labels: 버그, 백엔드

#323 [Bug] 회원가입 버그 해결
  backend/package-lock.json
  backend/src/main/java/com/woochacha/backend/domain/member/service/impl/SignServiceImpl.java
  frontend/.gitignore
  frontend/src/components/auth/SignupForm.js
Labels: 버그, 프론트엔드, 백엔드

#320 [Design] 매물 상세페이지 UI 구현
  frontend/package-lock.json
  frontend/src/components/product/ImageSlider.js
  frontend/src/pages/product/detail/[productId].js
Labels: 프론트엔드, 디자인

#316 [hackathon] 개인정보 비식별화 decoding 코드 추가
  backend/src/main/java/com/woochacha/backend/common/DataMasking.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/magageProduct/ManageProductFormDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/manageMember/MemberInfoDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/manageMember/MemberInfoListResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/manageMember/MemberLogDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/dto/manageMember/PurchaseMemberInfoResponseDto.java
  backend/src/main/java/com/woochacha/backend/domain/admin/repository/ManageProductFormRepository.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/ManageMemberServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/ManageProductFormServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/ManageTransactionServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/member/service/impl/SignServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/mypage/service/impl/MypageServiceImpl.java
Labels: 기능, 백엔드, 수정

#324 [Hackathon] 사용자의 중복 요청 방지 과제
  frontend/src/components/admin/AdminMenuAppbar.js
  frontend/src/components/admin/AdminpageSidebar.js
  frontend/src/components/auth/LoginForm.js
  frontend/src/components/common/ApproveModal.js
  frontend/src/components/common/LoadingBar.js
  frontend/src/components/common/MenuAppbar.js
  frontend/src/components/mypage/MypageSidebar.js
  frontend/src/layouts/DefaultHeader.js
  frontend/src/pages/admin/members/[memberId]/index.js
  frontend/src/pages/admin/members/edit/[memberId].js
  frontend/src/pages/admin/sales/approve/[saleformId].js
  frontend/src/pages/admin/sales/register/[saleformId].js
  frontend/src/pages/product/sale.js
  frontend/src/services/authApi.js
Labels: 기능, 프론트엔드, 수정

#319 [chore] QLDB 코드 정리
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/ApproveSaleServiceImpl.java
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/RegisterProductServiceImpl.java
Labels: 리팩터링, 백엔드, 수정

#326 [feature] 사용자 페이지 UI 수정
  frontend/next.config.js
  frontend/public/assets/images/defaultCarImg.svg
  frontend/public/assets/images/woochacha-404.svg
  frontend/public/assets/images/woochacha-nodata.svg
  frontend/src/components/admin/AdminpageSidebar.js
  frontend/src/components/admin/MemberTable.js
  frontend/src/components/admin/ProductTable.js
  frontend/src/components/admin/PurchaseTable.js
  frontend/src/components/admin/SaleTable.js
  frontend/src/components/auth/LoginForm.js
  frontend/src/components/auth/SignupForm.js
  frontend/src/components/common/LoadingBar.js
  frontend/src/components/common/LoadingBar.module.css
  frontend/src/components/common/NoData.js
  frontend/src/components/common/NoData.module.css
  frontend/src/components/common/SubTabMenu.js
  frontend/src/components/mypage/MypageCardEdit.js
  frontend/src/components/mypage/MypageCardPurchase.js
  frontend/src/components/mypage/MypageProfile.js
  frontend/src/components/mypage/MypageProfile.module.css
  frontend/src/components/mypage/MypageProfileEdit.js
  frontend/src/components/mypage/MypageSidebar.js
  frontend/src/constants/string.js
  frontend/src/layouts/DefaultFooter.js
  frontend/src/layouts/DefaultHeader.js
  frontend/src/layouts/admin/AdminPageLayout.js
  frontend/src/layouts/user/UserMyPageLayout.js
  frontend/src/pages/404.js
  frontend/src/pages/404.module.css
  frontend/src/pages/admin/members/[memberId]/index.js
  frontend/src/pages/admin/members/edit/[memberId].js
  frontend/src/pages/admin/members/index.js
  frontend/src/pages/admin/members/log/[memberId].js
  frontend/src/pages/admin/product/edit/[productId].js
  frontend/src/pages/admin/product/index.js
  frontend/src/pages/admin/purchase/index.js
  frontend/src/pages/admin/sales/index.js
  frontend/src/pages/admin/sales/register/[saleformId].js
  frontend/src/pages/capitals/index.js
  frontend/src/pages/index.js
  frontend/src/pages/mypage/[userId].js
  frontend/src/pages/mypage/profile/edit/[userId].js
  frontend/src/pages/mypage/purchase-request/[userId].js
  frontend/src/pages/mypage/purchase/[userId].js
  frontend/src/pages/mypage/registered/[userId].js
  frontend/src/pages/mypage/registered/edit.js
  frontend/src/pages/mypage/sale-request/[userId].js
  frontend/src/pages/mypage/sale/[userId].js
  frontend/src/pages/product/detail/[productId].js
  frontend/src/pages/product/index.js
  frontend/src/pages/product/sale.js
  frontend/src/styles/globals.css
Labels: 프론트엔드, 디자인, 수정

#328 [Test] 판매 관련 통합 테스트 코드 작성
  backend/src/main/java/com/woochacha/backend/domain/admin/service/impl/RegisterProductServiceImpl.java
  frontend/cypress.config.js
  frontend/cypress/e2e/sale.cy.js
  frontend/cypress/image/test1.png
  frontend/cypress/image/test2.png
  frontend/cypress/image/test3.png
  frontend/cypress/image/test4.png
  frontend/cypress/support/commands.js
  frontend/cypress/support/e2e.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/product/sale.js
Labels: 버그, 프론트엔드, 테스트

#330 [feat] 메인 홈페이지 무한 스크롤 구현
  frontend/src/pages/index.js
Labels: 기능, 프론트엔드

#331 [design] 관리자 페이지 UI 수정
  frontend/src/components/product/MainProduct.js
  frontend/src/components/product/MainProduct.module.css
  frontend/src/layouts/DefaultHeader.js
  frontend/src/pages/404.js
  frontend/src/pages/_document.js
  frontend/src/pages/admin/sales/approve/[saleformId].js
  frontend/src/pages/admin/sales/approve/approve.module.css
  frontend/src/pages/admin/sales/register/[saleformId].js
  frontend/src/pages/admin/sales/register/register.module.css
  frontend/src/pages/capitals/index.js
  frontend/src/pages/index.js
  frontend/src/pages/main.module.css
Labels: 프론트엔드, 디자인, 수정

#333 [refactor] seo 관련 태그 수정 및 추가
  frontend/public/assets/images/favicon.ico
  frontend/src/components/auth/SignupForm.js
  frontend/src/components/product/DetailImageSlider.js
  frontend/src/layouts/DefaultHeader.js
  frontend/src/pages/_document.js
  frontend/src/pages/admin/sales/approve/[saleformId].js
  frontend/src/pages/admin/sales/register/[saleformId].js
  frontend/src/pages/index.js
  frontend/src/pages/product/index.js
Labels: 리팩터링, 프론트엔드, 수정

#335 [style] 상세 페이지 UI 수정
  frontend/src/components/product/ImageSlider.js
  frontend/src/pages/product/detail/[productId].js
Labels: 리팩터링, 프론트엔드, 디자인, 수정

#338 [Docs] README.md 초안 작성
  README.md
  docs/back-skills.png
  docs/front-skills.png
  docs/infra.png
  docs/loan.png
  docs/logo2.png
  docs/qldb.png
  docs/sale.png
  docs/save.png
  docs/wooritown.png
Labels: 문서 작성
